#!/usr/bin/env php
<?php

namespace AgilezenToRedmine;

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application();
$app->addCommands([
    new Command\Export(),
]);
$app->run();
