#!/usr/bin/env php
<?php

namespace AgileZenToRedmine;

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

error_reporting(-1);

$app = new Application();
$app->addCommands([
    new Command\DownloadAttachments(),
    new Command\Export(),
    new Command\Import(),
    new Command\MapPhasesToStatuses(),
]);
$app->run();
